import './catalog'
import './catalogFilters'
import './catalogFilter'
import './catalogAside'
import './catalogNav'

import './catalog.scss'
import './catalogFilters.scss'
import './catalogFilter.scss'
import './catalogAside.scss'
import './catalogNav.scss'
import './catalogBanner.scss'
import './catalogPagination.scss'
