<?php namespace App;
// категории и подкатегории для модального окна каталога
$categories = [
  [
    'title' => 'Кабели силовые',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели информационные',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Подбор кабеля',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Спецкабель',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели судовые',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели монтажные',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели сварочные',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели самонесущие',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели Витая пара',
    'url' => '/catalog/',
  ],
  [
    'title' => 'Кабели высоковольтные',
    'url' => '/catalog/',
  ],
//  [
//    'title' => 'Провода',
//    'url' => '/catalog/',
//  ],
];
$subCategories = [
  /** кабели силовые */
  [
    [
      'category' => [
        'title' => 'Изоляция и оболочка',
        'url' => '/catalog/',
      ],
      'items' => [
        [
          'title' => 'С пластмассовой изоляцией',
          'url' => '/catalog/',],
        [
          'title' => 'С бумажной изоляцией БПИ',
          'url' => '/catalog/',],
        [
          'title' => 'С резиновой изоляцией',
          'url' => '/catalog/',],
        [
          'title' => 'С ПВХ оболочкой',
          'url' => '/catalog/',],
        [
          'title' => 'Безгалогенный',
          'url' => '/catalog/',],
        [
          'title' => 'С изоляцией из сшитого полиэтилена',
          'url' => '/catalog/',],
        [
          'title' => 'FRLS',
          'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'Часто ищут', 'url' => '#'],
      'items' => [
        ['title' => 'Экранированные', 'url' => '/catalog/',],
        ['title' => 'Бронированные', 'url' => '/catalog/',],
        ['title' => 'Огнестойкие', 'url' => '/catalog/',],
        ['title' => 'Негорючие', 'url' => '/catalog/',],
        ['title' => 'Морозостойкие', 'url' => '/catalog/',],
        ['title' => 'Плоские', 'url' => '/catalog/',],
        ['title' => 'Гибкие', 'url' => '/catalog/',],
        ['title' => 'С тросом', 'url' => '/catalog/',],
        ['title' => 'Сварочные', 'url' => '/catalog/',],
        ['title' => 'Без брони', 'url' => '/catalog/',],
        ['title' => 'Для питания', 'url' => '/catalog/',],
        ['title' => 'Для проводки', 'url' => '/catalog/',],
        ['title' => 'Для освещения', 'url' => '/catalog/',],],
    ],
    [
      'category' => ['title' => 'Популярные марки ', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'ВВГНГ', 'url' => '/catalog/',],
        ['title' => 'ВВГ', 'url' => '/catalog/',],
        ['title' => 'ВВГнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'АВВГнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'ВВГ-Пнг(А)', 'url' => '/catalog/',],
        ['title' => 'ВВГ-П', 'url' => '/catalog/',],
        ['title' => 'АВВГ', 'url' => '/catalog/',],
        ['title' => 'ВБбШв', 'url' => '/catalog/',],
        ['title' => 'ВБШвнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'NUM', 'url' => '/catalog/',],],
    ],
    [
      'category' => ['title' => 'По количеству жил', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Одножильные', 'url' => '/catalog/',],
        ['title' => 'Двухжильные', 'url' => '/catalog/',],
        ['title' => 'Трехжильные', 'url' => '/catalog/',],
        ['title' => 'Четырехжильные', 'url' => '/catalog/',],
        ['title' => 'Пятижильные', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'Материал жилы', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Алюминиевые силовые', 'url' => '/catalog/',],
        ['title' => 'Медные силовые', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'По напряжению ', 'url' => '/catalog/',],
      'items' => [
        ['title' => '1 кВ', 'url' => '/catalog/',],
        ['title' => '6 кВ', 'url' => '/catalog/',],
        ['title' => '10 кВ', 'url' => '/catalog/',],
        ['title' => '35 кВ', 'url' => '/catalog/',],
        ['title' => '110 кВ', 'url' => '/catalog/',],],
    ],
  ],
  /** кабели информационные */
  [
    [
      'category' => ['title' => 'Контрольные', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Все контрольные кабели', 'url' => '/catalog/',],
        ['title' => 'КВВГ', 'url' => '/catalog/',],
        ['title' => 'КВВГЭ', 'url' => '/catalog/',],
        ['title' => 'КВВГнг(А)', 'url' => '/catalog/',],
        ['title' => 'КВВГЭнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'КВВГнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'КВБбШв', 'url' => '/catalog/',],
        ['title' => 'КППГнг(А)-HF', 'url' => '/catalog/',],
        ['title' => 'КВБбШвнг(А)', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'Управления', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Все кабели управления', 'url' => '/catalog/',],
        ['title' => 'КУПЭВ', 'url' => '/catalog/',],
        ['title' => 'КПВ', 'url' => '/catalog/',],
        ['title' => 'КУГВВ', 'url' => '/catalog/',],
        ['title' => 'КУПВ', 'url' => '/catalog/',],
        ['title' => 'КУПР', 'url' => '/catalog/',],
        ['title' => 'КУПЭВнг(А)-LS-ХЛ', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'Часто ищут', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Высокочастотные', 'url' => '/catalog/',],
        ['title' => 'Для компьютерных сетей', 'url' => '/catalog/',],
        ['title' => 'Радиочастотные', 'url' => '/catalog/',],
        ['title' => 'Кабели связи', 'url' => '/catalog/',],
        ['title' => 'Витая пара', 'url' => '/catalog/',],
        ['title' => 'Сетевые', 'url' => '/catalog/',],
        ['title' => 'Слаботочные', 'url' => '/catalog/',],
        ['title' => 'Симметричные', 'url' => '/catalog/',],
        ['title' => 'Антенные', 'url' => '/catalog/',],
        ['title' => 'Кабели FTP', 'url' => '/catalog/',],
        ['title' => 'Кабели UTP', 'url' => '/catalog/',],
      ],
    ],
  ],
  /** подбор кабеля */
  [
    [
      'category' => ['title' => 'По назначению', 'url' => '#'],
      'items' => [
        ['title' => 'Шахтные', 'url' => '#'],
        ['title' => 'Монтажные', 'url' => '#'],
        ['title' => 'Универсальные', 'url' => '#'],
        ['title' => 'Автомобильные', 'url' => '#'],
        ['title' => 'Сварочные', 'url' => '#'],
        ['title' => 'Подводные', 'url' => '#'],
        ['title' => 'Для пожарной и охранной сигнализации', 'url' => '#'],
        ['title' => 'Для сигнализации и блокировки', 'url' => '#'],
        ['title' => 'Для автоматизации систем управления', 'url' => '#'],
        ['title' => 'Водопогружные', 'url' => '#'],
        ['title' => 'Высоковольтные', 'url' => '#'],
        ['title' => 'Для локальной сети', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'По свойствам', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Медные', 'url' => '/catalog/',],
        ['title' => 'Алюминиевые', 'url' => '/catalog/',],
        ['title' => 'Бронированные', 'url' => '/catalog/',],
        ['title' => 'Экранированные', 'url' => '/catalog/',],
        ['title' => 'Неэкранированные', 'url' => '/catalog/',],
        ['title' => 'Кабели с тросом', 'url' => '/catalog/',],
        ['title' => 'Водопогружные', 'url' => '/catalog/',],
        ['title' => 'Самонесущие', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'По исполнению', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Огнестойкие', 'url' => '/catalog/',],
        ['title' => 'Морозостойкие', 'url' => '/catalog/',],
        ['title' => 'Не распространяющие горение', 'url' => '/catalog/',],
        ['title' => 'Безгалогеновые', 'url' => '/catalog/',],
        ['title' => 'Плоские', 'url' => '/catalog/',],
        ['title' => 'Герметичные', 'url' => '/catalog/',],
        ['title' => 'Водонепроницаемые', 'url' => '/catalog/',],
        ['title' => 'Тропические', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'По количеству жил', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Одножильные', 'url' => '/catalog/',],
        ['title' => 'Двухжильные', 'url' => '/catalog/',],
        ['title' => 'Трехжильные', 'url' => '/catalog/',],
        ['title' => 'Четырехжильные', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'По зоне прокладки', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'Для воздушной прокладки', 'url' => '/catalog/',],
        ['title' => 'Для внутренней прокладки', 'url' => '/catalog/',],
        ['title' => 'Для внешней прокладки', 'url' => '/catalog/',],
        ['title' => 'Для подземной прокладки', 'url' => '/catalog/',],
        ['title' => 'Подобрать по другим', 'url' => '/catalog/',],
      ],
    ],
  ],
  /** спец кабель */
  [
    [
      'category' => [
        'title' => 'Кабель для Минобороны РФ',
        'url' => '/catalog/',
      ],
    ],
  ],
  /** кабели судовые */
  [
    [
      'category' => ['title' => 'Все судовые кабели', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПЭВ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПЭВЭ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭВ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КНР', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КНРЭ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КСНРТЭл', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КСРТнг(А)', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'МРШМ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'МРШНЭ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'НГРШМ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'НРШМ', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'НРШМЭнг(С)-FRHF', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВнг(А)-LS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭВнг(А)-LS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭнг(А)-LS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВВЭВнг(А)-FRLS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВВЭнг(А)-FRLS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭВнг(А)-FRLS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПВЭВЭВнг(А)-FRLS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПЭВнг(А)-LS', 'url' => '/catalog/',],
    ],
    [
      'category' => ['title' => 'КМПЭВЭВнг(А)-LS', 'url' => '/catalog/',],
    ],
  ],
  /** кабели монтажные */
  [
    ['category' => ['title' => 'Все монтажные кабели', 'url' => '#'],],
    ['category' => ['title' => 'КУПсЭВнг(А)-FRLS', 'url' => '#'],],
    ['category' => ['title' => 'КУПсЭВнг(А)-LS', 'url' => '#'],],
    ['category' => ['title' => 'КУПсЭПнг(А)-FRHF', 'url' => '#'],],
    ['category' => ['title' => 'КУПсЭПнг(А)-HF', 'url' => '#'],],
    ['category' => ['title' => 'КУПсЭПнг(А)-HF-ХЛ', 'url' => '#'],],
    ['category' => ['title' => 'КЭВВнг(А)-LS', 'url' => '#'],],
    ['category' => ['title' => 'КЭВЭВнг(А)-LS', 'url' => '#'],],
  ],
  /** кабели сварочные */
  [
    ['category' => ['title' => 'Все сварочные кабели', 'url' => '#'],],
    ['category' => ['title' => 'КГ', 'url' => '#'],],
    ['category' => ['title' => 'КГ-ХЛ', 'url' => '#'],],
    ['category' => ['title' => 'КГН', 'url' => '#'],],
    ['category' => ['title' => 'КОГ1', 'url' => '#'],],
    ['category' => ['title' => 'КОГ1-ХЛ', 'url' => '#'],],
  ],
  /** кабели самонесущие */
  [
    ['category' => ['title' => 'Все самонесущие кабели', 'url' => '/catalog/',],],
    ['category' => ['title' => 'АПвПТи', 'url' => '/catalog/',],],
    ['category' => ['title' => 'АПвПгТп', 'url' => '/catalog/',],],
  ],
  /** кабели витая пара */
  [
    [
      'category' => ['title' => 'Все кабели Витая пара', 'url' => '#'],
      'items' => [
        ['title' => 'КИПвЭВнг(А)-LS', 'url' => '#'],
        ['title' => 'КСПвЭнг(А)-HF', 'url' => '#'],
        ['title' => 'Лоутокс КПСВВнг(А)-LSLTx', 'url' => '#'],
        ['title' => 'СПЕЦЛАН FTP-5нг(А)-FRHF', 'url' => '#'],
        ['title' => 'СПЕЦЛАН UTP-3нг(А)-FRLSLTx', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'Витая пара категории 5е', 'url' => '#'],
      'items' => [
        ['title' => 'КВПГЭфнг(А)-5e-БГ', 'url' => '#'],
        ['title' => 'КВПМЭКГнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'КВПМЭКнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'КВПМЭнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'КВПМЭУКГнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'КВПМЭУКнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'КВПМЭУнг(А)-5е-БГ', 'url' => '#'],
        ['title' => 'Лоутокс КВПнг(C)-LSLTx-5e', 'url' => '#'],
        ['title' => 'СПЕЦЛАН F/UTP Cat 5e PVC', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'Витая пара категории 6', 'url' => '#'],
      'items' => [
        ['title' => 'КВПЭГ-6нг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭГКГ-6нг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭГУ-6нг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭГУКГ-6нг(А)-БГ', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'Витая пара категории 7', 'url' => '#'],
      'items' => [
        ['title' => 'КВПЭ-7нг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭУ-7нг(А)-БГ', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'Витая пара категории 6А', 'url' => '#'],
      'items' => [
        ['title' => 'КВПМЭ-6Анг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПМЭКГ-6Анг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПМЭУ-6Анг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПМЭУКГ-6Анг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭКГнг(А)-6A-БГ', 'url' => '#'],
        ['title' => 'КВПЭнг(А)-6A-БГ', 'url' => '#'],
      ],
    ],
    [
      'category' => ['title' => 'Витая пара категории 7А', 'url' => '#'],
      'items' => [
        ['title' => 'КВПЭ-7Aнг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭКГ-7Aнг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭУ-7Aнг(А)-БГ', 'url' => '#'],
        ['title' => 'КВПЭУКГ-7Aнг(А)-БГ', 'url' => '#'],
      ],
    ],
  ],
  /** кабели высоковольтные */
  [
    [
      'category' => ['title' => 'Все высоковольтные кабели', 'url' => '/catalog/',],
      'items' => [
        ['title' => '64 кВ', 'url' => '/catalog/',],
        ['title' => '110 кВ', 'url' => '/catalog/',],
        ['title' => '220 кВ', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'С алюминиевой жилой', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'АПвВ', 'url' => '/catalog/',],
        ['title' => 'АПвВнг(А)', 'url' => '/catalog/',],
        ['title' => 'АПвКП2г', 'url' => '/catalog/',],
        ['title' => 'АПвКПг', 'url' => '/catalog/',],
        ['title' => 'АПвПг', 'url' => '/catalog/',],
        ['title' => 'АПвПу2г', 'url' => '/catalog/',],
        ['title' => 'АПвПуг', 'url' => '/catalog/',],
      ],
    ],
    [
      'category' => ['title' => 'С медной жилой', 'url' => '/catalog/',],
      'items' => [
        ['title' => 'ПвВ', 'url' => '/catalog/',],
        ['title' => 'ПвВнг(А)', 'url' => '/catalog/',],
        ['title' => 'ПвВнг(А)-LS', 'url' => '/catalog/',],
        ['title' => 'ПвКПг', 'url' => '/catalog/',],
        ['title' => 'ПвП2г', 'url' => '/catalog/',],
        ['title' => 'ПвПг', 'url' => '/catalog/',],
        ['title' => 'ПвПнг(А)-HF', 'url' => '/catalog/',],
      ],
    ],
  ],
];

// массив товаров для тестирования
$fakeProducts = [
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => true,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '5 000',
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель КШВЭББШВ-6 3х95+1х10+1х16, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => 0,
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '120 000',
    'priceOld' => '133 000',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => true,
    'parameters' => [],
  ],
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '120 000',
    'priceOld' => '133 000',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '846857434',
    'url' => '/product/',
    'price' => 0,
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => false,
    'isOrderAble' => false,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '34564536',
    'url' => '/product/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => false,
    'isOrderAble' => false,
    'isHit' => true,
    'parameters' => [],
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '123421423',
    'url' => '/product/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель КШВЭББШВ-6 3х95+1х10+1х16, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '51 000',
    'priceOld' => '62 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '5 000',
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель КШВЭББШВ-6 3х95+1х10+1х16, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => 0,
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
    'parameters' => [
      ['key' => 'Экран', 'value' => 'Нет',],
      ['key' => 'Холодостойкий', 'value' => 'Нет',],
      ['key' => 'Материал жилы', 'value' => 'Медь',],
      ['key' => 'Материал изоляции', 'value' => 'ПВХ',],
      ['key' => 'Гибкий', 'value' => 'Нет',],
      ['key' => 'Количество жил', 'value' => '5',],
    ],
  ],
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'code' => '95342345',
    'url' => '/product/',
    'price' => '120 000',
    'priceOld' => '133 000',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => true,
    'parameters' => [],
  ],
];

// города для модального окна города и выбора города
$citiesPopular = [
  'Москва',
  'Санкт-Петербург',
  'Новосибирск',
  'Екатеринбург',
  'Казань',
  'Нижний Новгород',
  'Красноярск',
  'Челябинск',
  'Самара',
  'Уфа',
  'Ростов-на-Дону',
  'Краснодар',
  'Омск',
  'Воронеж',
  'Пермь',
  'Волгоград',
];
$citiesAll = [
  'Абакан',
  'Адыгейск',
  'Амурск',
  'Анадырь',
  'Апатиты',
  'Арзамас',
  'Архангельск',
  'Астрахань',
  'Ачинск',
  'Балашиха',
  'Барнаул',
  'Белгород',
  'Бердск',
  'Бийск',
  'Биробиджан',
  'Благовещенск',
  'Бокситогорск',
  'Братск',
  'Брянск',
  'Бузулук',
  'Великие Луки',
  'Великий Новгород',
  'Великий Устюг',
  'Верхоянск',
  'Владивосток',
  'Владикавказ',
  'Владимир',
  'Волгоград',
  'Вологда',
  'Воркута',
  'Воронеж',
  'Воткинск',
  'Всеволожск',
  'Выборг',
  'Вышний Волочёк',
  'Гатчина',
  'Геленджик',
  'Глазов',
  'Горно-Алтайск',
  'Грозный',
  'Гусь-Хрустальный',
  'Дзержинск',
  'Долгопрудный',
  'Донецк',
  'Екатеринбург',
  'Елабуга',
  'Елец',
  'Иваново',
  'Ижевск',
  'Иркутск',
  'Йошкар-Ола',
  'Казань',
  'Калининград',
  'Калуга',
  'Кемерово',
  'Керчь',
  'Кингисепп',
  'Киров',
  'Кировск',
  'Кисловодск',
  'Козельск',
  'Коломна',
  'Комсомольск-на-Амуре',
  'Кондопога',
  'Королёв',
  'Кострома',
  'Котлас',
  'Красногорск',
  'Краснодар',
  'Красноярск',
  'Куйбышев',
  'Курган',
  'Курильск',
  'Курск',
  'Кызыл',
  'Лахденпохья',
  'Липецк',
  'Лодейное Поле',
  'Луга',
  'Люберцы',
  'Магадан',
  'Магас',
  'Магнитогорск',
  'Майкоп',
  'Махачкала',
  'Миасс',
  'Алейск',
  'Минусинск',
  'Мирный',
  'Москва',
  'Мурманск',
  'Муром',
  'Мытищи',
  'Набережные',
  'Челны',
  'Назрань',
  'Нальчик',
  'Нарьян-Мар',
  'Находка',
  'Нефтекамск',
  'Нефтеюганск',
  'Нижневартовск',
  'Нижнекамск',
  'Нижний Новгород',
  'Нижний Тагил',
  'Новокузнецк',
  'Новороссийск',
  'Новосибирск',
  'Новочеркасск',
  'Новый Уренгой',
  'Норильск',
  'Ноябрьск',
  'Обнинск',
  'Одинцово',
  'Омск',
  'Орёл',
  'Оренбург',
  'Орск',
  'Остров',
  'Пенза',
  'Переславль-Залесский',
  'Пермь',
  'Петрозаводск',
  'Петропавловск-Камчатский',
  'Подольск',
  'Приозерск',
  'Псков',
  'Пятигорск',
  'Раменское',
  'Реутов',
  'Ржев',
  'Россошь',
  'Ростов',
  'Ростов-на-Дону',
  'Рыбинск',
  'Рязань',
  'Салават',
  'Салехард',
  'Самара',
  'Санкт-Петербург',
  'Саранск',
  'Саратов',
  'Саров',
  'Саяногорск',
  'Северодвинск',
  'Североморск',
  'Североуральск',
  'Серпухов',
  'Смоленск',
  'Советск',
  'Соликамск',
  'Сортавала',
  'Сосновый Бор',
  'Сосногорск',
  'Сочи',
  'Спасск',
  'Ставрополь',
  'Старый Оскол',
  'Суздаль',
  'Сургут',
  'Сызрань',
  'Сыктывкар',
  'Таганрог',
  'Тамбов',
  'Тверь',
  'Тихвин',
  'Тобольск',
  'Тольятти',
  'Томск',
  'Тула',
  'Тында',
  'Тюмень',
  'Углич',
  'Улан-Удэ',
  'Ульяновск',
  'Уссурийск',
  'Уфа',
  'Ухта',
  'Хабаровск',
  'Ханты-Мансийск',
  'Химки',
  'Чаплыгин',
  'Чебоксары',
  'Челябинск',
  'Череповец',
  'Черкесск',
  'Чёрмоз',
  'Чита',
  'Чусовой',
  'Щёлково',
  'Электросталь',
  'Элиста',
  'Энгельс',
  'Южно-Сахалинск',
  'Якутск',
  'Ярославль',

];
$cityCurrent = 'Санкт-Петербург';

$isAuth = Router::$params->get('auth') == 'true';
$isCartEmpty = Router::$params->get('cart_empty') == 'true';

$cartItemsQuantity = 3;
