<?php namespace App;

$home = new Page([
  'title' => 'Главная',
  'metaDescription' => 'Заполните описание мета',
  'metaKeywords' => 'Заполните ключевые поля мета',
  'url' => '/',
  'view' => 'home',
  'parent' => null,
]);
$catalog = new Page([
  'title' => 'Каталог',
  'metaDescription' => 'Заполните описание мета',
  'metaKeywords' => 'Заполните ключевые поля мета',
  'url' => '/catalog/',
  'view' => 'catalog',
  'parent' => $home,
]);
$product = new Page([
  'title' => 'Страница продукта',
  'metaDescription' => 'Заполните описание мета',
  'metaKeywords' => 'Заполните ключевые поля мета',
  'url' => '/product/',
  'view' => 'product',
  'parent' => $catalog,
]);

$pages = [
  $home, $catalog, $product,
];

$pageNotFound = new Page([
  'title' => 'Страница не найдена',
  'metaDescription' => 'Заполните описание мета',
  'metaKeywords' => 'Заполните ключевые поля мета',
  'url' => null,
  'view' => '404',
  'parent' => $home,
]);
$page = $pageNotFound;
foreach ($pages as $p) {
  if (Router::$currentRoute == $p->url) {
    $page = $p;
  }
}

$fakeProducts = [
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'url' => '/product/test3/',
    'price' => '120 000',
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => true,
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'url' => '/product/test/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => false,
    'isOrderAble' => false,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'url' => '/product/test/',
    'price' => '5 000',
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель КШВЭББШВ-6 3х95+1х10+1х16, 1 кВ',
    'url' => '/product/test2/',
    'price' => 0,
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'url' => '/product/test3/',
    'price' => '120 000',
    'priceOld' => '133 000',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_4.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => true,
  ],
  [
    'title' => 'Кабель СШВ 3х150+1х120, 1 кВ',
    'url' => '/product/test3/',
    'price' => '120 000',
    'priceOld' => '133 000',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_3.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'url' => '/product/test/',
    'price' => 0,
    'priceOld' => 0,
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => false,
    'isOrderAble' => false,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'url' => '/product/test/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => false,
    'isOrderAble' => false,
    'isHit' => true,
  ],
  [
    'title' => 'Кабель NYM-J 3х1,5, 1 кВ',
    'url' => '/product/test/',
    'price' => '5 000',
    'priceOld' => '6 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => true,
    'isRecommended' => true,
    'isOrderAble' => false,
    'isHit' => false,
  ],
  [
    'title' => 'Кабель КШВЭББШВ-6 3х95+1х10+1х16, 1 кВ',
    'url' => '/product/test2/',
    'price' => '51 000',
    'priceOld' => '62 400',
    'images' => [
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_1.jpg',
        'alt' => 'img description',
      ],
      [
        'url' => 'https://cable.ru/images/resize/catalog/cable/800_vbbshv_cores_2.jpg',
        'alt' => 'img description',
      ],
    ],
    'isInStock' => false,
    'isRecommended' => false,
    'isOrderAble' => true,
    'isHit' => false,
  ],
];
$citiesPopular = [
  'Москва',
  'Санкт-Петербург',
  'Новосибирск',
  'Екатеринбург',
  'Казань',
  'Нижний Новгород',
  'Красноярск',
  'Челябинск',
  'Самара',
  'Уфа',
  'Ростов-на-Дону',
  'Краснодар',
  'Омск',
  'Воронеж',
  'Пермь',
  'Волгоград',
];
$citiesAll = [
  'Абакан',
  'Адыгейск',
  'Амурск',
  'Анадырь',
  'Апатиты',
  'Арзамас',
  'Архангельск',
  'Астрахань',
  'Ачинск',
  'Балашиха',
  'Барнаул',
  'Белгород',
  'Бердск',
  'Бийск',
  'Биробиджан',
  'Благовещенск',
  'Бокситогорск',
  'Братск',
  'Брянск',
  'Бузулук',
  'Великие Луки',
  'Великий Новгород',
  'Великий Устюг',
  'Верхоянск',
  'Владивосток',
  'Владикавказ',
  'Владимир',
  'Волгоград',
  'Вологда',
  'Воркута',
  'Воронеж',
  'Воткинск',
  'Всеволожск',
  'Выборг',
  'Вышний Волочёк',
  'Гатчина',
  'Геленджик',
  'Глазов',
  'Горно-Алтайск',
  'Грозный',
  'Гусь-Хрустальный',
  'Дзержинск',
  'Долгопрудный',
  'Донецк',
  'Екатеринбург',
  'Елабуга',
  'Елец',
  'Иваново',
  'Ижевск',
  'Иркутск',
  'Йошкар-Ола',
  'Казань',
  'Калининград',
  'Калуга',
  'Кемерово',
  'Керчь',
  'Кингисепп',
  'Киров',
  'Кировск',
  'Кисловодск',
  'Козельск',
  'Коломна',
  'Комсомольск-на-Амуре',
  'Кондопога',
  'Королёв',
  'Кострома',
  'Котлас',
  'Красногорск',
  'Краснодар',
  'Красноярск',
  'Куйбышев',
  'Курган',
  'Курильск',
  'Курск',
  'Кызыл',
  'Лахденпохья',
  'Липецк',
  'Лодейное Поле',
  'Луга',
  'Люберцы',
  'Магадан',
  'Магас',
  'Магнитогорск',
  'Майкоп',
  'Махачкала',
  'Миасс',
  'Алейск',
  'Минусинск',
  'Мирный',
  'Москва',
  'Мурманск',
  'Муром',
  'Мытищи',
  'Набережные',
  'Челны',
  'Назрань',
  'Нальчик',
  'Нарьян-Мар',
  'Находка',
  'Нефтекамск',
  'Нефтеюганск',
  'Нижневартовск',
  'Нижнекамск',
  'Нижний Новгород',
  'Нижний Тагил',
  'Новокузнецк',
  'Новороссийск',
  'Новосибирск',
  'Новочеркасск',
  'Новый Уренгой',
  'Норильск',
  'Ноябрьск',
  'Обнинск',
  'Одинцово',
  'Омск',
  'Орёл',
  'Оренбург',
  'Орск',
  'Остров',
  'Пенза',
  'Переславль-Залесский',
  'Пермь',
  'Петрозаводск',
  'Петропавловск-Камчатский',
  'Подольск',
  'Приозерск',
  'Псков',
  'Пятигорск',
  'Раменское',
  'Реутов',
  'Ржев',
  'Россошь',
  'Ростов',
  'Ростов-на-Дону',
  'Рыбинск',
  'Рязань',
  'Салават',
  'Салехард',
  'Самара',
  'Санкт-Петербург',
  'Саранск',
  'Саратов',
  'Саров',
  'Саяногорск',
  'Северодвинск',
  'Североморск',
  'Североуральск',
  'Серпухов',
  'Смоленск',
  'Советск',
  'Соликамск',
  'Сортавала',
  'Сосновый Бор',
  'Сосногорск',
  'Сочи',
  'Спасск',
  'Ставрополь',
  'Старый Оскол',
  'Суздаль',
  'Сургут',
  'Сызрань',
  'Сыктывкар',
  'Таганрог',
  'Тамбов',
  'Тверь',
  'Тихвин',
  'Тобольск',
  'Тольятти',
  'Томск',
  'Тула',
  'Тында',
  'Тюмень',
  'Углич',
  'Улан-Удэ',
  'Ульяновск',
  'Уссурийск',
  'Уфа',
  'Ухта',
  'Хабаровск',
  'Ханты-Мансийск',
  'Химки',
  'Чаплыгин',
  'Чебоксары',
  'Челябинск',
  'Череповец',
  'Черкесск',
  'Чёрмоз',
  'Чита',
  'Чусовой',
  'Щёлково',
  'Электросталь',
  'Элиста',
  'Энгельс',
  'Южно-Сахалинск',
  'Якутск',
  'Ярославль',

];
$cityCurrent = 'Санкт-Петербург';

