import 'src/components/sections/advantages'
// import 'src/components/sections/banners'
// import 'src/components/sections/breadcrumbs'
// import 'src/components/sections/cookie'
// import 'src/components/sections/footer'
// import 'src/components/sections/forms'
import 'src/components/sections/header'
// import 'src/components/sections/hero'
// import 'src/components/sections/menu'
// import 'src/components/sections/promo'
import 'src/components/sections/search'
// import 'src/components/sections/section'
