export interface iElements {
  form: HTMLElement,
  title: HTMLElement,
  discount: HTMLElement,
  slider: HTMLElement,
  slidesContainer: HTMLElement,
  sliderButtonPrev: HTMLElement,
  sliderButtonNext: HTMLElement,
  pricesContainer: HTMLElement,
  priceOld: HTMLElement,
  price: HTMLElement,
  colorsContainer: HTMLElement,
  colorButtons: HTMLElement[],
  sizesContainer: HTMLElement,
  sizeButtons: HTMLElement[],
  submit: HTMLElement,
}

export interface iSelectors {
  form: string,
  title: string,
  discount: string,
  slider: string,
  slidesContainer: string,
  sliderButtonPrev: string,
  sliderButtonNext: string,
  pricesContainer: string,
  priceOld: string,
  price: string,
  colorsContainer: string,
  colorButton: string,
  sizesContainer: string,
  sizeButton: string,
  submit: string,
}
